openapi: 3.1.0
info:
  version: 1.0.0
  title: Products app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 
    This is a documentation of students app
tags:
  - name: Products
    description: Operations about.
  - name: Cart
    description: Operations cart.
  - name: User
    description: Operations register.
  - name: Stores
    description: Operations stores.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /api/cart:
    put: 
      $ref: "../swagger/path/carts/put.yaml"
    get: 
      $ref: "../swagger/path/carts/get.yaml"
  /api/products:
    get: 
      $ref: "../swagger/path/products/get.yaml"
  /api/products/{id}:
    get: 
      $ref: "../swagger/path/products/{id}/get.yaml" 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer