
  type: object
  required:
    - _id
    - name
    - suppliers
    - stock
    - price
    - category
    - photo
  properties:
    _id:
      description: "Product ID"
      type: string
      example: "65e4decdd286b30065d54af9"
    name:
      description: "Product name"
      type: string
      example: "Apple iPhone 13"
    suppliers:
      description: "Product supplier"
      type: string
      example: "Apple Inc."
    stock:
      description: "Available stock quantity"
      type: number
      example: 150
    price:
      description: "Product price in USD"
      type: number
      example: 999.99
    category:
      description: "Product category"
      type: string
      example: "Electronics"
    photo:
      description: "Product image URL"
      type: string
      example: "https://example.com/image.jpg"
    reviews:
      description: "List of product reviews"
      type: array
      items:
        type: object
        required:
          - user
          - rating
          - comment
        properties:
          user:
            description: "Reviewer’s user ID or name"
            type: string
            example: "john_doe"
          rating:
            description: "Star rating from 1 to 5"
            type: number
            minimum: 1
            maximum: 5
            example: 4
          comment:
            description: "Review text"
            type: string
            example: "Great phone with excellent battery life."